apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: env
spec:
  version: {{ .TagName }}
  homepage: https://github.com/almariah/kubectl-env
  shortDescription: Allow templating kustomize manifests using environment variables
  description: |
    The kubectl-env plugin will allow templating kustomize manifests using environment variables.
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/almariah/kubectl-env/releases/download/{{ .TagName }}/kubectl-env_{{ .TagName }}_darwin_amd64.tar.gz" .TagName }}
    bin: kubectl-env
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/almariah/kubectl-env/releases/download/{{ .TagName }}/kubectl-env_{{ .TagName }}_linux_amd64.tar.gz" .TagName }}
    bin: kubectl-env
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/almariah/kubectl-env/releases/download/{{ .TagName }}/kubectl-env_{{ .TagName }}_windows_amd64.tar.gz" .TagName }}
    bin: kubectl-env.exe
